name: Github Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v1
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-py${{ matrix.python-version }}-pip-

    - uses: actions/cache@v1
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-py${{ matrix.python-version }}-pip-

    - uses: actions/cache@v1
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-py${{ matrix.python-version }}-pip-

    - name: Install style dependencies
      if: matrix.python-version == 3.9
      run: |
        python -m pip install --upgrade pip
        pip install flake8 isort>=5 black>=20.8b1
    - name: Build
      run: |
        python setup.py build_ext --inplace
        pip install .[test]
    - name: Lint with flake8
      if: matrix.python-version == 3.9
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --statistics
    - name: Check import sorting with isort
      if: matrix.python-version == 3.9
      run: |
        isort -c --df .
    - name: Check formatting with black
      if: matrix.python-version == 3.9
      run: |
        black . --check --exclude "(build/|dist/|\.git/|\.mypy_cache/|\.tox/|\.venv/\.asv/|env|\.eggs)"
    - name: Check formatting with clang-format
      if: (matrix.python-version == 3.9) && (startsWith(runner.os, 'Linux'))
      run: |
        clang-format -i --style=file bottleneck/**/*.c bottleneck/**/*.h
        git diff --exit-code
    - name: Test with pytest
      run: |
        pytest
  armv64_job:
    name: Build and Test for arm64
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false      
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Install and test bottleneck
      run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt update && \
              apt install -y python3.8 && \
              apt install -y python3.8-venv && \
              python3.8 -m venv .env && \
              source .env/bin/activate && \
              python -m pip install --upgrade pip && \
              apt-get update && \
              apt install -y build-essential && \
              apt-get install -y python3.8-dev && \
              python setup.py build_ext --inplace && \
              pip install .[test] && \
              python -m pip install pytest && \
              pytest && \
              deactivate'
